### PR TITLE
Merge pull request #3 from frainworks/master

### PR DESCRIPTION
**Pull request by SnO2WMaN**
Fix Apache

### CODE REVIEW

**Comment by snowhite0804** [comment]
before marge, what you've changed?
github says "Files changed:0"

**Comment by EbXpJ6bp** [comment]
Will we need lines 27-32?

**Comment by snowhite0804** [comment]
google analyze codes?
maybe we need later.

**Comment by EbXpJ6bp** [comment]
see line 176-179

**Comment by snowhite0804** [comment]
aw, don't need line 27-32....

**Pull request closed without merging**
